version: "3.8"

services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db

  backend:
#    build: ./backend
    image: ghizodak/reactprisma-backend
    ports:
      - "4000:4000"
    volumes:
      - logs:/app/logs
      - ./backend:/app
    depends_on:
      - mongodb

  frontend:
#    build: ./frontend
    image: ghizodak/reactprisma-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs:
